package www.panda.com.mall.model;

import java.util.ArrayList;

import www.panda.com.mall.R;
import www.panda.com.mall.entity.MyProduct;
import www.panda.com.mall.entity.MySection;

public enum DataDemoUtils {

    Singleton;

    public ArrayList<MySection> getData(ArrayList<MySection> list){
        list.clear();
        list.add(new MySection(true, "A"));
        list.add(new MySection(new MyProduct("Abc", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Air", R.drawable.one)));
        list.add(new MySection(new MyProduct("Apple", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Acomplishment", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Avoide", R.drawable.five)));
        list.add(new MySection(new MyProduct("Acheive", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Ability", R.drawable.two)));
        list.add(new MySection(true, "B"));
        list.add(new MySection(new MyProduct("Baby", R.drawable.five)));
        list.add(new MySection(new MyProduct("Background", R.drawable.six)));
        list.add(new MySection(new MyProduct("Bake", R.drawable.one)));
        list.add(new MySection(true, "C"));
        list.add(new MySection(new MyProduct("Cabbage", R.drawable.six)));
        list.add(new MySection(new MyProduct("Cafe", R.drawable.five)));
        list.add(new MySection(new MyProduct("Cafeteria", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Calendar", R.drawable.three)));
        list.add(new MySection(new MyProduct("Car", R.drawable.four)));
        list.add(new MySection(new MyProduct("Carpenter", R.drawable.two)));
        list.add(new MySection(new MyProduct("Carry", R.drawable.four)));
        list.add(new MySection(new MyProduct("Case", R.drawable.three)));
        list.add(new MySection(true, "D"));
        list.add(new MySection(new MyProduct("Decade", R.drawable.five)));
        list.add(new MySection(new MyProduct("Decorate", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Deer", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Delicious", R.drawable.four)));
        list.add(new MySection(new MyProduct("Definition", R.drawable.five)));
        list.add(new MySection(new MyProduct("Define", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Delicious", R.drawable.six)));
        list.add(new MySection(new MyProduct("Data", R.drawable.two)));
        list.add(new MySection(true, "E"));
        list.add(new MySection(new MyProduct("Even", R.drawable.ten)));
        list.add(new MySection(new MyProduct("East", R.drawable.six)));
        list.add(new MySection(new MyProduct("Each", R.drawable.five)));
        list.add(new MySection(new MyProduct("Eagle", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Eaglet", R.drawable.two)));
        list.add(new MySection(new MyProduct("Eye", R.drawable.eight)));
        list.add(new MySection(true, "F"));
        list.add(new MySection(new MyProduct("Friend", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Fabulous", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Fantasise", R.drawable.two)));
        list.add(new MySection(new MyProduct("Fantastic", R.drawable.five)));
        list.add(new MySection(new MyProduct("Frater", R.drawable.six)));
        list.add(new MySection(true, "G"));
        list.add(new MySection(new MyProduct("Galvanocautery", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Gabardine", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Gain", R.drawable.one)));
        list.add(new MySection(new MyProduct("Gaze", R.drawable.five)));
        list.add(new MySection(new MyProduct("Gift", R.drawable.six)));
        list.add(new MySection(true, "H"));
        list.add(new MySection(new MyProduct("Heart", R.drawable.two)));
        list.add(new MySection(new MyProduct("Haberdashery", R.drawable.three)));
        list.add(new MySection(true, "I"));
        list.add(new MySection(new MyProduct("Iceberg", R.drawable.three)));
        list.add(new MySection(new MyProduct("Iambic", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Ice", R.drawable.two)));
        list.add(new MySection(new MyProduct("Idea", R.drawable.six)));
        list.add(new MySection(new MyProduct("Icebreaker", R.drawable.one)));
        list.add(new MySection(new MyProduct("Ibis", R.drawable.ten)));
        list.add(new MySection(true, "J"));
        list.add(new MySection(new MyProduct("Jabber", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Jack", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Jabot", R.drawable.ten)));
        list.add(new MySection(true, "K"));
        list.add(new MySection(new MyProduct("Kail", R.drawable.four)));
        list.add(new MySection(new MyProduct("Kaiser", R.drawable.five)));
        list.add(new MySection(true, "L"));
        list.add(new MySection(new MyProduct("Labeled", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Laboratory", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Labour", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Lace", R.drawable.six)));
        list.add(new MySection(new MyProduct("Lack", R.drawable.eight)));
        list.add(new MySection(true, "M"));
        list.add(new MySection(new MyProduct("Mabel", R.drawable.two)));
        list.add(new MySection(new MyProduct("Macadam", R.drawable.ten)));
        list.add(new MySection(true, "N"));
        list.add(new MySection(new MyProduct("Naiad", R.drawable.five)));
        list.add(new MySection(new MyProduct("Nation", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Narrow", R.drawable.nine)));
        list.add(new MySection(true, "O"));
        list.add(new MySection(new MyProduct("Oaken", R.drawable.four)));
        list.add(new MySection(new MyProduct("Oakum", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Observe", R.drawable.six)));
        list.add(new MySection(new MyProduct("Object", R.drawable.three)));
        list.add(new MySection(new MyProduct("Obey", R.drawable.ten)));
        list.add(new MySection(true, "P"));
        list.add(new MySection(new MyProduct("Pabulum", R.drawable.one)));
        list.add(new MySection(new MyProduct("Pear", R.drawable.two)));
        list.add(new MySection(new MyProduct("Pace", R.drawable.ten)));
        list.add(new MySection(true, "Q"));
        list.add(new MySection(new MyProduct("Quack", R.drawable.three)));
        list.add(new MySection(new MyProduct("Quad", R.drawable.nine)));
        list.add(new MySection(true, "R"));
        list.add(new MySection(new MyProduct("Rabbi", R.drawable.two)));
        list.add(new MySection(new MyProduct("Rabbit", R.drawable.five)));
        list.add(new MySection(new MyProduct("Really", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Railway", R.drawable.six)));
        list.add(new MySection(true, "S"));
        list.add(new MySection(new MyProduct("Saber", R.drawable.three)));
        list.add(new MySection(new MyProduct("Sable", R.drawable.one)));
        list.add(new MySection(new MyProduct("Surprised", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Small", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Smart", R.drawable.three)));
        list.add(new MySection(true, "T"));
        list.add(new MySection(new MyProduct("Table", R.drawable.one)));
        list.add(new MySection(new MyProduct("Tag", R.drawable.six)));
        list.add(new MySection(new MyProduct("Talent", R.drawable.ten)));
        list.add(new MySection(true, "U"));
        list.add(new MySection(new MyProduct("Ubiquitous", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Umbrella", R.drawable.two)));
        list.add(new MySection(true, "V"));
        list.add(new MySection(new MyProduct("Vacant", R.drawable.three)));
        list.add(new MySection(new MyProduct("Vacuum", R.drawable.five)));
        list.add(new MySection(new MyProduct("Vacation", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Vague ", R.drawable.four)));
        list.add(new MySection(new MyProduct("Vain", R.drawable.eight)));
        list.add(new MySection(true, "W"));
        list.add(new MySection(new MyProduct("Wacky", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Wad", R.drawable.two)));
        list.add(new MySection(true, "X"));
        list.add(new MySection(new MyProduct("Xalloy", R.drawable.three)));
        list.add(new MySection(new MyProduct("Xanadu", R.drawable.two)));
        list.add(new MySection(new MyProduct("Xenidium", R.drawable.ten)));
        list.add(new MySection(true, "Y"));
        list.add(new MySection(new MyProduct("Yacht", R.drawable.three)));
        list.add(new MySection(new MyProduct("Yak", R.drawable.five)));
        list.add(new MySection(new MyProduct("Yarn", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Yaw", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Yeast", R.drawable.six)));
        list.add(new MySection(new MyProduct("Yippee", R.drawable.eight)));
        list.add(new MySection(true, "Z"));
        list.add(new MySection(new MyProduct("Zany", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Zealous", R.drawable.six)));
        list.add(new MySection(new MyProduct("Zap", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Zeal ", R.drawable.one)));
        list.add(new MySection(new MyProduct("Zip", R.drawable.three)));
        list.add(new MySection(new MyProduct("Zion", R.drawable.four)));
        list.add(new MySection(new MyProduct("Zigzag", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Zest", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Zenith", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Zephyr", R.drawable.two)));
        list.add(new MySection(new MyProduct("Zero", R.drawable.one)));
        list.add(new MySection(new MyProduct("Zebra", R.drawable.four)));
        list.add(new MySection(new MyProduct("Zipcode", R.drawable.five)));
        list.add(new MySection(new MyProduct("Zipper", R.drawable.six)));
        list.add(new MySection(new MyProduct("Zither", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Zone", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Zoo", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Zoom", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Zoologist", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Zoos", R.drawable.ten)));

        return list;
    }

    public ArrayList<MySection> getData0(ArrayList<MySection> list){
        list.clear();
        list.add(new MySection(true, "IPhone"));
        list.add(new MySection(new MyProduct("iphone6", R.drawable.two)));
        list.add(new MySection(new MyProduct("iphone7", R.drawable.two)));
        list.add(new MySection(new MyProduct("iphone8", R.drawable.two)));
        list.add(new MySection(new MyProduct("iphoneX", R.drawable.two)));
        list.add(new MySection(new MyProduct("iphoneXS", R.drawable.two)));
        list.add(new MySection(new MyProduct("ip XS MAX", R.drawable.two)));
        list.add(new MySection(new MyProduct("iphoneXR", R.drawable.two)));
        list.add(new MySection(true, "Huawei"));
        list.add(new MySection(new MyProduct("HuaweiP20", R.drawable.one)));
        list.add(new MySection(new MyProduct("HuaweiM20", R.drawable.one)));
        list.add(new MySection(new MyProduct("HuaweiM10", R.drawable.one)));
        list.add(new MySection(true, "Xiaomi"));
        list.add(new MySection(new MyProduct("xiaomi1", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi2", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi3", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi4", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi5", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi6", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi7", R.drawable.three)));
        list.add(new MySection(new MyProduct("xiaomi8", R.drawable.three)));
        list.add(new MySection(true, "oppo"));
        list.add(new MySection(new MyProduct("oppoR9", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR10", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR11", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR12", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR14", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR15", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR16", R.drawable.four)));
        list.add(new MySection(new MyProduct("oppoR17", R.drawable.four)));
        list.add(new MySection(true, "vivo"));
        list.add(new MySection(new MyProduct("vivoX17", R.drawable.five)));
        list.add(new MySection(new MyProduct("vivoX18", R.drawable.five)));
        list.add(new MySection(new MyProduct("vivoX19", R.drawable.five)));
        list.add(new MySection(new MyProduct("vivoX20", R.drawable.five)));
        list.add(new MySection(new MyProduct("vivoX21", R.drawable.five)));
        list.add(new MySection(new MyProduct("vivoX22", R.drawable.five)));
        list.add(new MySection(true, "samsung"));
        list.add(new MySection(new MyProduct("samsungS1", R.drawable.six)));
        list.add(new MySection(new MyProduct("samsungS2", R.drawable.six)));
        list.add(new MySection(new MyProduct("samsungS3", R.drawable.six)));
        list.add(new MySection(new MyProduct("samsungS4", R.drawable.six)));
        list.add(new MySection(new MyProduct("samsungS5", R.drawable.six)));
        return list;
    }

    public ArrayList<MySection> getData1(ArrayList<MySection> list){
        list.clear();
        list.add(new MySection(true, "Women's Dress"));
        list.add(new MySection(new MyProduct("Dress", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.seven)));
        list.add(new MySection(new MyProduct("T-Shirt", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.eight)));
        list.add(new MySection(new MyProduct("TARA", R.drawable.seven)));
        list.add(new MySection(new MyProduct("H&M", R.drawable.ten)));
        list.add(new MySection(true, "Men's Wear"));
        list.add(new MySection(new MyProduct("Dress", R.drawable.ten)));
        list.add(new MySection(new MyProduct("T-Shirt", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.seven)));
        list.add(new MySection(true, "Men's Clothes"));
        list.add(new MySection(new MyProduct("xiaomi1", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Dress", R.drawable.seven)));
        list.add(new MySection(new MyProduct("T-Shirt", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Dress", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Dress", R.drawable.nine)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.seven)));
        list.add(new MySection(true, "Men's Coat"));
        list.add(new MySection(new MyProduct("T-Shirt", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.eight)));
        list.add(new MySection(new MyProduct("H&M", R.drawable.eight)));
        list.add(new MySection(new MyProduct("TARA", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.nine)));
        list.add(new MySection(new MyProduct("H&M", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.eight)));
        list.add(new MySection(true, "Men's Jacket"));
        list.add(new MySection(new MyProduct("H&M", R.drawable.seven)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.seven)));
        list.add(new MySection(new MyProduct("TARA", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.nine)));
        list.add(new MySection(true, "Women's Skirt"));
        list.add(new MySection(new MyProduct("Jeans", R.drawable.eight)));
        list.add(new MySection(new MyProduct("Shirt", R.drawable.ten)));
        list.add(new MySection(new MyProduct("Topa", R.drawable.seven)));
        list.add(new MySection(new MyProduct("T-Shirt", R.drawable.nine)));
        list.add(new MySection(new MyProduct("TARA", R.drawable.seven)));
        return list;
    }
}
